// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="predict_predict,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.264000,HLS_SYN_LAT=730,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=2257,HLS_SYN_LUT=3699,HLS_VERSION=2023_2}" *)

module predict (
        ap_clk,
        ap_rst_n,
        input_stream_TDATA,
        input_stream_TVALID,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] input_stream_TDATA;
input   input_stream_TVALID;
output   input_stream_TREADY;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [1:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [4:0] input_stream_TID;
input  [5:0] input_stream_TDEST;
output  [31:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [3:0] output_stream_TKEEP;
output  [3:0] output_stream_TSTRB;
output  [1:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [4:0] output_stream_TID;
output  [5:0] output_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [4:0] l1_bias_address0;
reg    l1_bias_ce0;
wire   [15:0] l1_bias_q0;
wire   [4:0] l2_bias_address0;
reg    l2_bias_ce0;
wire   [15:0] l2_bias_q0;
reg    output_stream_TDATA_blk_n;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire   [5:0] add_ln32_fu_464_p2;
reg   [5:0] add_ln32_reg_701;
wire    ap_CS_fsm_state5;
wire   [8:0] add_ln38_8_fu_482_p2;
reg   [8:0] add_ln38_8_reg_706;
wire   [1:0] trunc_ln32_fu_498_p1;
reg   [1:0] trunc_ln32_reg_718;
wire    ap_CS_fsm_state6;
reg   [2:0] lshr_ln1_reg_722;
wire   [4:0] trunc_ln45_fu_559_p1;
reg   [4:0] trunc_ln45_reg_735;
wire    ap_CS_fsm_state8;
wire   [5:0] add_ln45_fu_570_p2;
reg   [5:0] add_ln45_reg_743;
wire   [7:0] tmp_2_fu_576_p3;
reg   [7:0] tmp_2_reg_748;
wire   [1:0] trunc_ln45_1_fu_589_p1;
reg   [1:0] trunc_ln45_1_reg_753;
wire    ap_CS_fsm_state9;
reg   [2:0] lshr_ln2_reg_757;
reg   [3:0] input_layer_address0;
reg    input_layer_ce0;
reg    input_layer_we0;
wire   [31:0] input_layer_q0;
reg    input_layer_ce1;
wire   [31:0] input_layer_q1;
reg   [3:0] input_layer_1_address0;
reg    input_layer_1_ce0;
reg    input_layer_1_we0;
wire   [31:0] input_layer_1_q0;
reg    input_layer_1_ce1;
wire   [31:0] input_layer_1_q1;
reg   [3:0] input_layer_2_address0;
reg    input_layer_2_ce0;
reg    input_layer_2_we0;
wire   [31:0] input_layer_2_q0;
reg    input_layer_2_ce1;
wire   [31:0] input_layer_2_q1;
reg   [3:0] input_layer_3_address0;
reg    input_layer_3_ce0;
reg    input_layer_3_we0;
wire   [31:0] input_layer_3_q0;
reg    input_layer_3_ce1;
wire   [31:0] input_layer_3_q1;
reg   [2:0] hidden_layer1_address0;
reg    hidden_layer1_ce0;
reg    hidden_layer1_we0;
wire   [30:0] hidden_layer1_q0;
reg    hidden_layer1_ce1;
wire   [30:0] hidden_layer1_q1;
reg   [2:0] hidden_layer1_1_address0;
reg    hidden_layer1_1_ce0;
reg    hidden_layer1_1_we0;
wire   [30:0] hidden_layer1_1_q0;
reg    hidden_layer1_1_ce1;
wire   [30:0] hidden_layer1_1_q1;
reg   [2:0] hidden_layer1_2_address0;
reg    hidden_layer1_2_ce0;
reg    hidden_layer1_2_we0;
wire   [30:0] hidden_layer1_2_q0;
reg    hidden_layer1_2_ce1;
wire   [30:0] hidden_layer1_2_q1;
reg   [2:0] hidden_layer1_3_address0;
reg    hidden_layer1_3_ce0;
reg    hidden_layer1_3_we0;
wire   [30:0] hidden_layer1_3_q0;
reg    hidden_layer1_3_ce1;
wire   [30:0] hidden_layer1_3_q1;
reg   [2:0] hidden_layer2_address0;
reg    hidden_layer2_ce0;
reg    hidden_layer2_we0;
wire   [30:0] hidden_layer2_q0;
reg    hidden_layer2_ce1;
wire   [30:0] hidden_layer2_q1;
reg   [2:0] hidden_layer2_1_address0;
reg    hidden_layer2_1_ce0;
reg    hidden_layer2_1_we0;
wire   [30:0] hidden_layer2_1_q0;
reg    hidden_layer2_1_ce1;
wire   [30:0] hidden_layer2_1_q1;
reg   [2:0] hidden_layer2_2_address0;
reg    hidden_layer2_2_ce0;
reg    hidden_layer2_2_we0;
wire   [30:0] hidden_layer2_2_q0;
reg    hidden_layer2_2_ce1;
wire   [30:0] hidden_layer2_2_q1;
reg   [2:0] hidden_layer2_3_address0;
reg    hidden_layer2_3_ce0;
reg    hidden_layer2_3_we0;
wire   [30:0] hidden_layer2_3_q0;
reg    hidden_layer2_3_ce1;
wire   [30:0] hidden_layer2_3_q1;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_done;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_idle;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_ready;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_ce0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_we0;
wire   [31:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_d0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_ce0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_we0;
wire   [31:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_d0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_ce0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_we0;
wire   [31:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_d0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_ce0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_we0;
wire   [31:0] grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_d0;
wire    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_stream_TREADY;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_done;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_idle;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_ready;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_ce0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_ce1;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_ce0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_ce1;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_ce0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_ce1;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_ce0;
wire   [3:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_ce1;
wire   [31:0] grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_trunc_ln38_3_out;
wire    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_trunc_ln38_3_out_ap_vld;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_done;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_idle;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_ready;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_ce0;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_ce1;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_ce0;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_ce1;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_ce0;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_ce1;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_address0;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_ce0;
wire   [2:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_address1;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_ce1;
wire   [31:0] grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_p_out;
wire    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_p_out_ap_vld;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_done;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_idle;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_ready;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_address0;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_ce0;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_address1;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_ce1;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_address0;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_ce0;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_address1;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_ce1;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_address0;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_ce0;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_address1;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_ce1;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_address0;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_ce0;
wire   [2:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_address1;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_ce1;
wire   [31:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_max_22_out;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_max_22_out_ap_vld;
wire   [31:0] grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_output_layer_1_11_out;
wire    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_output_layer_1_11_out_ap_vld;
reg    grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start_reg;
wire   [0:0] icmp_ln32_fu_458_p2;
reg   [31:0] trunc_ln38_3_loc_fu_164;
reg    grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start_reg;
wire   [0:0] icmp_ln45_fu_564_p2;
reg    grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start_reg;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln32_fu_494_p1;
wire   [63:0] zext_ln32_1_fu_510_p1;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln45_fu_585_p1;
wire   [63:0] zext_ln45_1_fu_601_p1;
wire    ap_CS_fsm_state10;
reg   [5:0] j_fu_148;
reg   [5:0] j_1_fu_216;
wire   [30:0] select_ln41_fu_540_p3;
wire   [30:0] select_ln54_fu_631_p3;
wire   [8:0] tmp_1_fu_474_p3;
wire   [8:0] zext_ln38_fu_470_p1;
wire  signed [31:0] sext_ln40_fu_520_p1;
wire   [31:0] add_ln40_fu_524_p2;
wire   [0:0] icmp_ln41_fu_534_p2;
wire   [30:0] trunc_ln41_fu_530_p1;
wire  signed [31:0] sext_ln53_fu_611_p1;
wire   [31:0] add_ln53_fu_615_p2;
wire   [0:0] icmp_ln54_fu_625_p2;
wire   [30:0] trunc_ln54_fu_621_p1;
wire   [0:0] out_data_fu_653_p2;
wire    regslice_both_output_stream_V_data_V_U_apdone_blk;
reg    ap_block_state13;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    regslice_both_input_stream_V_data_V_U_apdone_blk;
wire   [31:0] input_stream_TDATA_int_regslice;
wire    input_stream_TVALID_int_regslice;
reg    input_stream_TREADY_int_regslice;
wire    regslice_both_input_stream_V_data_V_U_ack_in;
wire    regslice_both_input_stream_V_keep_V_U_apdone_blk;
wire   [3:0] input_stream_TKEEP_int_regslice;
wire    regslice_both_input_stream_V_keep_V_U_vld_out;
wire    regslice_both_input_stream_V_keep_V_U_ack_in;
wire    regslice_both_input_stream_V_strb_V_U_apdone_blk;
wire   [3:0] input_stream_TSTRB_int_regslice;
wire    regslice_both_input_stream_V_strb_V_U_vld_out;
wire    regslice_both_input_stream_V_strb_V_U_ack_in;
wire    regslice_both_input_stream_V_user_V_U_apdone_blk;
wire   [1:0] input_stream_TUSER_int_regslice;
wire    regslice_both_input_stream_V_user_V_U_vld_out;
wire    regslice_both_input_stream_V_user_V_U_ack_in;
wire    regslice_both_input_stream_V_last_V_U_apdone_blk;
wire   [0:0] input_stream_TLAST_int_regslice;
wire    regslice_both_input_stream_V_last_V_U_vld_out;
wire    regslice_both_input_stream_V_last_V_U_ack_in;
wire    regslice_both_input_stream_V_id_V_U_apdone_blk;
wire   [4:0] input_stream_TID_int_regslice;
wire    regslice_both_input_stream_V_id_V_U_vld_out;
wire    regslice_both_input_stream_V_id_V_U_ack_in;
wire    regslice_both_input_stream_V_dest_V_U_apdone_blk;
wire   [5:0] input_stream_TDEST_int_regslice;
wire    regslice_both_input_stream_V_dest_V_U_vld_out;
wire    regslice_both_input_stream_V_dest_V_U_ack_in;
wire   [31:0] output_stream_TDATA_int_regslice;
reg    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_V_data_V_U_vld_out;
wire    regslice_both_output_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_output_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_keep_V_U_vld_out;
wire    regslice_both_output_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_output_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_strb_V_U_vld_out;
wire    regslice_both_output_stream_V_user_V_U_apdone_blk;
wire   [1:0] output_stream_TUSER_int_regslice;
wire    regslice_both_output_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_user_V_U_vld_out;
wire    regslice_both_output_stream_V_last_V_U_apdone_blk;
wire    regslice_both_output_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_last_V_U_vld_out;
wire    regslice_both_output_stream_V_id_V_U_apdone_blk;
wire   [4:0] output_stream_TID_int_regslice;
wire    regslice_both_output_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_id_V_U_vld_out;
wire    regslice_both_output_stream_V_dest_V_U_apdone_blk;
wire   [5:0] output_stream_TDEST_int_regslice;
wire    regslice_both_output_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start_reg = 1'b0;
#0 grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start_reg = 1'b0;
#0 grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start_reg = 1'b0;
#0 grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start_reg = 1'b0;
#0 j_fu_148 = 6'd0;
#0 j_1_fu_216 = 6'd0;
end

predict_l1_bias_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
l1_bias_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(l1_bias_address0),
    .ce0(l1_bias_ce0),
    .q0(l1_bias_q0)
);

predict_l2_bias_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
l2_bias_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(l2_bias_address0),
    .ce0(l2_bias_ce0),
    .q0(l2_bias_q0)
);

predict_input_layer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
input_layer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_layer_address0),
    .ce0(input_layer_ce0),
    .we0(input_layer_we0),
    .d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_d0),
    .q0(input_layer_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_address1),
    .ce1(input_layer_ce1),
    .q1(input_layer_q1)
);

predict_input_layer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
input_layer_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_layer_1_address0),
    .ce0(input_layer_1_ce0),
    .we0(input_layer_1_we0),
    .d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_d0),
    .q0(input_layer_1_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_address1),
    .ce1(input_layer_1_ce1),
    .q1(input_layer_1_q1)
);

predict_input_layer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
input_layer_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_layer_2_address0),
    .ce0(input_layer_2_ce0),
    .we0(input_layer_2_we0),
    .d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_d0),
    .q0(input_layer_2_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_address1),
    .ce1(input_layer_2_ce1),
    .q1(input_layer_2_q1)
);

predict_input_layer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
input_layer_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_layer_3_address0),
    .ce0(input_layer_3_ce0),
    .we0(input_layer_3_we0),
    .d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_d0),
    .q0(input_layer_3_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_address1),
    .ce1(input_layer_3_ce1),
    .q1(input_layer_3_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer1_address0),
    .ce0(hidden_layer1_ce0),
    .we0(hidden_layer1_we0),
    .d0(select_ln41_fu_540_p3),
    .q0(hidden_layer1_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_address1),
    .ce1(hidden_layer1_ce1),
    .q1(hidden_layer1_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer1_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer1_1_address0),
    .ce0(hidden_layer1_1_ce0),
    .we0(hidden_layer1_1_we0),
    .d0(select_ln41_fu_540_p3),
    .q0(hidden_layer1_1_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_address1),
    .ce1(hidden_layer1_1_ce1),
    .q1(hidden_layer1_1_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer1_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer1_2_address0),
    .ce0(hidden_layer1_2_ce0),
    .we0(hidden_layer1_2_we0),
    .d0(select_ln41_fu_540_p3),
    .q0(hidden_layer1_2_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_address1),
    .ce1(hidden_layer1_2_ce1),
    .q1(hidden_layer1_2_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer1_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer1_3_address0),
    .ce0(hidden_layer1_3_ce0),
    .we0(hidden_layer1_3_we0),
    .d0(select_ln41_fu_540_p3),
    .q0(hidden_layer1_3_q0),
    .address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_address1),
    .ce1(hidden_layer1_3_ce1),
    .q1(hidden_layer1_3_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer2_address0),
    .ce0(hidden_layer2_ce0),
    .we0(hidden_layer2_we0),
    .d0(select_ln54_fu_631_p3),
    .q0(hidden_layer2_q0),
    .address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_address1),
    .ce1(hidden_layer2_ce1),
    .q1(hidden_layer2_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer2_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer2_1_address0),
    .ce0(hidden_layer2_1_ce0),
    .we0(hidden_layer2_1_we0),
    .d0(select_ln54_fu_631_p3),
    .q0(hidden_layer2_1_q0),
    .address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_address1),
    .ce1(hidden_layer2_1_ce1),
    .q1(hidden_layer2_1_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer2_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer2_2_address0),
    .ce0(hidden_layer2_2_ce0),
    .we0(hidden_layer2_2_we0),
    .d0(select_ln54_fu_631_p3),
    .q0(hidden_layer2_2_q0),
    .address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_address1),
    .ce1(hidden_layer2_2_ce1),
    .q1(hidden_layer2_2_q1)
);

predict_hidden_layer1_RAM_AUTO_1R1W #(
    .DataWidth( 31 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hidden_layer2_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(hidden_layer2_3_address0),
    .ce0(hidden_layer2_3_ce0),
    .we0(hidden_layer2_3_we0),
    .d0(select_ln54_fu_631_p3),
    .q0(hidden_layer2_3_q0),
    .address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_address1),
    .ce1(hidden_layer2_3_ce1),
    .q1(hidden_layer2_3_q1)
);

predict_predict_Pipeline_VITIS_LOOP_26_1 grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start),
    .ap_done(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_done),
    .ap_idle(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_idle),
    .ap_ready(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_ready),
    .input_stream_TVALID(input_stream_TVALID_int_regslice),
    .input_layer_3_address0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_address0),
    .input_layer_3_ce0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_ce0),
    .input_layer_3_we0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_we0),
    .input_layer_3_d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_d0),
    .input_layer_2_address0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_address0),
    .input_layer_2_ce0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_ce0),
    .input_layer_2_we0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_we0),
    .input_layer_2_d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_d0),
    .input_layer_1_address0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_address0),
    .input_layer_1_ce0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_ce0),
    .input_layer_1_we0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_we0),
    .input_layer_1_d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_d0),
    .input_layer_address0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_address0),
    .input_layer_ce0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_ce0),
    .input_layer_we0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_we0),
    .input_layer_d0(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_d0),
    .input_stream_TDATA(input_stream_TDATA_int_regslice),
    .input_stream_TREADY(grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP_int_regslice),
    .input_stream_TSTRB(input_stream_TSTRB_int_regslice),
    .input_stream_TUSER(input_stream_TUSER_int_regslice),
    .input_stream_TLAST(input_stream_TLAST_int_regslice),
    .input_stream_TID(input_stream_TID_int_regslice),
    .input_stream_TDEST(input_stream_TDEST_int_regslice)
);

predict_predict_Pipeline_VITIS_LOOP_35_2 grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start),
    .ap_done(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_done),
    .ap_idle(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_idle),
    .ap_ready(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_ready),
    .add_ln38_8(add_ln38_8_reg_706),
    .input_layer_address0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_address0),
    .input_layer_ce0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_ce0),
    .input_layer_q0(input_layer_q0),
    .input_layer_address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_address1),
    .input_layer_ce1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_ce1),
    .input_layer_q1(input_layer_q1),
    .input_layer_1_address0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_address0),
    .input_layer_1_ce0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_ce0),
    .input_layer_1_q0(input_layer_1_q0),
    .input_layer_1_address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_address1),
    .input_layer_1_ce1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_ce1),
    .input_layer_1_q1(input_layer_1_q1),
    .input_layer_2_address0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_address0),
    .input_layer_2_ce0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_ce0),
    .input_layer_2_q0(input_layer_2_q0),
    .input_layer_2_address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_address1),
    .input_layer_2_ce1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_ce1),
    .input_layer_2_q1(input_layer_2_q1),
    .input_layer_3_address0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_address0),
    .input_layer_3_ce0(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_ce0),
    .input_layer_3_q0(input_layer_3_q0),
    .input_layer_3_address1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_address1),
    .input_layer_3_ce1(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_ce1),
    .input_layer_3_q1(input_layer_3_q1),
    .trunc_ln38_3_out(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_trunc_ln38_3_out),
    .trunc_ln38_3_out_ap_vld(grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_trunc_ln38_3_out_ap_vld)
);

predict_predict_Pipeline_VITIS_LOOP_48_3 grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start),
    .ap_done(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_done),
    .ap_idle(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_idle),
    .ap_ready(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_ready),
    .j_1(trunc_ln45_reg_735),
    .hidden_layer1_address0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_address0),
    .hidden_layer1_ce0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_ce0),
    .hidden_layer1_q0(hidden_layer1_q0),
    .hidden_layer1_address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_address1),
    .hidden_layer1_ce1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_ce1),
    .hidden_layer1_q1(hidden_layer1_q1),
    .hidden_layer1_1_address0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_address0),
    .hidden_layer1_1_ce0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_ce0),
    .hidden_layer1_1_q0(hidden_layer1_1_q0),
    .hidden_layer1_1_address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_address1),
    .hidden_layer1_1_ce1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_ce1),
    .hidden_layer1_1_q1(hidden_layer1_1_q1),
    .hidden_layer1_2_address0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_address0),
    .hidden_layer1_2_ce0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_ce0),
    .hidden_layer1_2_q0(hidden_layer1_2_q0),
    .hidden_layer1_2_address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_address1),
    .hidden_layer1_2_ce1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_ce1),
    .hidden_layer1_2_q1(hidden_layer1_2_q1),
    .hidden_layer1_3_address0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_address0),
    .hidden_layer1_3_ce0(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_ce0),
    .hidden_layer1_3_q0(hidden_layer1_3_q0),
    .hidden_layer1_3_address1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_address1),
    .hidden_layer1_3_ce1(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_ce1),
    .hidden_layer1_3_q1(hidden_layer1_3_q1),
    .zext_ln51(tmp_2_reg_748),
    .p_out(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_p_out),
    .p_out_ap_vld(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_p_out_ap_vld)
);

predict_predict_Pipeline_matmul3_VITIS_LOOP_61_4 grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start),
    .ap_done(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_done),
    .ap_idle(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_idle),
    .ap_ready(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_ready),
    .hidden_layer2_address0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_address0),
    .hidden_layer2_ce0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_ce0),
    .hidden_layer2_q0(hidden_layer2_q0),
    .hidden_layer2_address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_address1),
    .hidden_layer2_ce1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_ce1),
    .hidden_layer2_q1(hidden_layer2_q1),
    .hidden_layer2_1_address0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_address0),
    .hidden_layer2_1_ce0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_ce0),
    .hidden_layer2_1_q0(hidden_layer2_1_q0),
    .hidden_layer2_1_address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_address1),
    .hidden_layer2_1_ce1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_ce1),
    .hidden_layer2_1_q1(hidden_layer2_1_q1),
    .hidden_layer2_2_address0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_address0),
    .hidden_layer2_2_ce0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_ce0),
    .hidden_layer2_2_q0(hidden_layer2_2_q0),
    .hidden_layer2_2_address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_address1),
    .hidden_layer2_2_ce1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_ce1),
    .hidden_layer2_2_q1(hidden_layer2_2_q1),
    .hidden_layer2_3_address0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_address0),
    .hidden_layer2_3_ce0(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_ce0),
    .hidden_layer2_3_q0(hidden_layer2_3_q0),
    .hidden_layer2_3_address1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_address1),
    .hidden_layer2_3_ce1(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_ce1),
    .hidden_layer2_3_q1(hidden_layer2_3_q1),
    .max_22_out(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_max_22_out),
    .max_22_out_ap_vld(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_max_22_out_ap_vld),
    .output_layer_1_11_out(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_output_layer_1_11_out),
    .output_layer_1_11_out_ap_vld(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_output_layer_1_11_out_ap_vld)
);

predict_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

predict_regslice_both #(
    .DataWidth( 32 ))
regslice_both_input_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TDATA),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_data_V_U_ack_in),
    .data_out(input_stream_TDATA_int_regslice),
    .vld_out(input_stream_TVALID_int_regslice),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_data_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TKEEP),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_keep_V_U_ack_in),
    .data_out(input_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream_V_keep_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_keep_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 4 ))
regslice_both_input_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TSTRB),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_strb_V_U_ack_in),
    .data_out(input_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream_V_strb_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_strb_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 2 ))
regslice_both_input_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TUSER),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_user_V_U_ack_in),
    .data_out(input_stream_TUSER_int_regslice),
    .vld_out(regslice_both_input_stream_V_user_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_user_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TLAST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_last_V_U_ack_in),
    .data_out(input_stream_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream_V_last_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_last_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 5 ))
regslice_both_input_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TID),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_id_V_U_ack_in),
    .data_out(input_stream_TID_int_regslice),
    .vld_out(regslice_both_input_stream_V_id_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_id_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 6 ))
regslice_both_input_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TDEST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_dest_V_U_ack_in),
    .data_out(input_stream_TDEST_int_regslice),
    .vld_out(regslice_both_input_stream_V_dest_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_dest_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_V_data_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_data_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd1),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_keep_V_U_ack_in_dummy),
    .data_out(output_stream_TKEEP),
    .vld_out(regslice_both_output_stream_V_keep_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_keep_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd1),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_strb_V_U_ack_in_dummy),
    .data_out(output_stream_TSTRB),
    .vld_out(regslice_both_output_stream_V_strb_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_strb_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 2 ))
regslice_both_output_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TUSER_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_user_V_U_ack_in_dummy),
    .data_out(output_stream_TUSER),
    .vld_out(regslice_both_output_stream_V_user_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_user_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_last_V_U_ack_in_dummy),
    .data_out(output_stream_TLAST),
    .vld_out(regslice_both_output_stream_V_last_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_last_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 5 ))
regslice_both_output_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TID_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_id_V_U_ack_in_dummy),
    .data_out(output_stream_TID),
    .vld_out(regslice_both_output_stream_V_id_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_id_V_U_apdone_blk)
);

predict_regslice_both #(
    .DataWidth( 6 ))
regslice_both_output_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDEST_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_dest_V_U_ack_in_dummy),
    .data_out(output_stream_TDEST),
    .vld_out(regslice_both_output_stream_V_dest_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start_reg <= 1'b1;
        end else if ((grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_ready == 1'b1)) begin
            grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln32_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start_reg <= 1'b1;
        end else if ((grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_ready == 1'b1)) begin
            grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln45_fu_564_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start_reg <= 1'b1;
        end else if ((grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_ready == 1'b1)) begin
            grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln45_fu_564_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start_reg <= 1'b1;
        end else if ((grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_ready == 1'b1)) begin
            grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        j_1_fu_216 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        j_1_fu_216 <= add_ln45_reg_743;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_148 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        j_fu_148 <= add_ln32_reg_701;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln32_reg_701 <= add_ln32_fu_464_p2;
        add_ln38_8_reg_706 <= add_ln38_8_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln45_reg_743 <= add_ln45_fu_570_p2;
        tmp_2_reg_748[7 : 3] <= tmp_2_fu_576_p3[7 : 3];
        trunc_ln45_reg_735 <= trunc_ln45_fu_559_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        lshr_ln1_reg_722 <= {{j_fu_148[4:2]}};
        trunc_ln32_reg_718 <= trunc_ln32_fu_498_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        lshr_ln2_reg_757 <= {{j_1_fu_216[4:2]}};
        trunc_ln45_1_reg_753 <= trunc_ln45_1_fu_589_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_trunc_ln38_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        trunc_ln38_3_loc_fu_164 <= grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_trunc_ln38_3_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state13))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((output_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state13)) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((output_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state13)) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_1_address0 = zext_ln32_1_fu_510_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_1_address0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_address0;
    end else begin
        hidden_layer1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_1_ce0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_ce0;
    end else begin
        hidden_layer1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_1_ce1 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_1_ce1;
    end else begin
        hidden_layer1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln32_reg_718 == 2'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        hidden_layer1_1_we0 = 1'b1;
    end else begin
        hidden_layer1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_2_address0 = zext_ln32_1_fu_510_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_2_address0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_address0;
    end else begin
        hidden_layer1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_2_ce0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_ce0;
    end else begin
        hidden_layer1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_2_ce1 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_2_ce1;
    end else begin
        hidden_layer1_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln32_reg_718 == 2'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        hidden_layer1_2_we0 = 1'b1;
    end else begin
        hidden_layer1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_3_address0 = zext_ln32_1_fu_510_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_3_address0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_address0;
    end else begin
        hidden_layer1_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_3_ce0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_ce0;
    end else begin
        hidden_layer1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_3_ce1 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_3_ce1;
    end else begin
        hidden_layer1_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln32_reg_718 == 2'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        hidden_layer1_3_we0 = 1'b1;
    end else begin
        hidden_layer1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_address0 = zext_ln32_1_fu_510_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_address0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_address0;
    end else begin
        hidden_layer1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        hidden_layer1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_ce0 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_ce0;
    end else begin
        hidden_layer1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        hidden_layer1_ce1 = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_hidden_layer1_ce1;
    end else begin
        hidden_layer1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln32_reg_718 == 2'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        hidden_layer1_we0 = 1'b1;
    end else begin
        hidden_layer1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_1_address0 = zext_ln45_1_fu_601_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_1_address0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_address0;
    end else begin
        hidden_layer2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_1_ce0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_ce0;
    end else begin
        hidden_layer2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_1_ce1 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_1_ce1;
    end else begin
        hidden_layer2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln45_1_reg_753 == 2'd1))) begin
        hidden_layer2_1_we0 = 1'b1;
    end else begin
        hidden_layer2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_2_address0 = zext_ln45_1_fu_601_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_2_address0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_address0;
    end else begin
        hidden_layer2_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_2_ce0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_ce0;
    end else begin
        hidden_layer2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_2_ce1 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_2_ce1;
    end else begin
        hidden_layer2_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln45_1_reg_753 == 2'd2))) begin
        hidden_layer2_2_we0 = 1'b1;
    end else begin
        hidden_layer2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_3_address0 = zext_ln45_1_fu_601_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_3_address0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_address0;
    end else begin
        hidden_layer2_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_3_ce0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_ce0;
    end else begin
        hidden_layer2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_3_ce1 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_3_ce1;
    end else begin
        hidden_layer2_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln45_1_reg_753 == 2'd3))) begin
        hidden_layer2_3_we0 = 1'b1;
    end else begin
        hidden_layer2_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_address0 = zext_ln45_1_fu_601_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_address0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_address0;
    end else begin
        hidden_layer2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hidden_layer2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_ce0 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_ce0;
    end else begin
        hidden_layer2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        hidden_layer2_ce1 = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_hidden_layer2_ce1;
    end else begin
        hidden_layer2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (trunc_ln45_1_reg_753 == 2'd0))) begin
        hidden_layer2_we0 = 1'b1;
    end else begin
        hidden_layer2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_1_address0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_1_address0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_address0;
    end else begin
        input_layer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_1_ce0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_1_ce0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_ce0;
    end else begin
        input_layer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_1_ce1 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_1_ce1;
    end else begin
        input_layer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_1_we0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_1_we0;
    end else begin
        input_layer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_2_address0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_2_address0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_address0;
    end else begin
        input_layer_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_2_ce0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_2_ce0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_ce0;
    end else begin
        input_layer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_2_ce1 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_2_ce1;
    end else begin
        input_layer_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_2_we0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_2_we0;
    end else begin
        input_layer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_3_address0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_3_address0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_address0;
    end else begin
        input_layer_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_3_ce0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_3_ce0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_ce0;
    end else begin
        input_layer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_3_ce1 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_3_ce1;
    end else begin
        input_layer_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_3_we0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_3_we0;
    end else begin
        input_layer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_address0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_address0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_address0;
    end else begin
        input_layer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_ce0 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_ce0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_ce0;
    end else begin
        input_layer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_layer_ce1 = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_input_layer_ce1;
    end else begin
        input_layer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_layer_we0 = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_layer_we0;
    end else begin
        input_layer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_TREADY_int_regslice = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_input_stream_TREADY;
    end else begin
        input_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        l1_bias_ce0 = 1'b1;
    end else begin
        l1_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        l2_bias_ce0 = 1'b1;
    end else begin
        l2_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY_int_regslice;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        output_stream_TVALID_int_regslice = 1'b1;
    end else begin
        output_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln32_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln45_fu_564_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((output_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if ((~((output_stream_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state13)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_464_p2 = (j_fu_148 + 6'd1);

assign add_ln38_8_fu_482_p2 = (tmp_1_fu_474_p3 + zext_ln38_fu_470_p1);

assign add_ln40_fu_524_p2 = ($signed(sext_ln40_fu_520_p1) + $signed(trunc_ln38_3_loc_fu_164));

assign add_ln45_fu_570_p2 = (j_1_fu_216 + 6'd1);

assign add_ln53_fu_615_p2 = ($signed(sext_ln53_fu_611_p1) + $signed(grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_p_out));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state13 = ((output_stream_TREADY_int_regslice == 1'b0) | (regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start = grp_predict_Pipeline_VITIS_LOOP_26_1_fu_373_ap_start_reg;

assign grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start = grp_predict_Pipeline_VITIS_LOOP_35_2_fu_395_ap_start_reg;

assign grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start = grp_predict_Pipeline_VITIS_LOOP_48_3_fu_413_ap_start_reg;

assign grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start = grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_ap_start_reg;

assign icmp_ln32_fu_458_p2 = ((j_fu_148 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_534_p2 = (($signed(add_ln40_fu_524_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_564_p2 = ((j_1_fu_216 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_625_p2 = (($signed(add_ln53_fu_615_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign input_stream_TREADY = regslice_both_input_stream_V_data_V_U_ack_in;

assign l1_bias_address0 = zext_ln32_fu_494_p1;

assign l2_bias_address0 = zext_ln45_fu_585_p1;

assign out_data_fu_653_p2 = (($signed(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_max_22_out) > $signed(grp_predict_Pipeline_matmul3_VITIS_LOOP_61_4_fu_432_output_layer_1_11_out)) ? 1'b1 : 1'b0);

assign output_stream_TDATA_int_regslice = out_data_fu_653_p2;

assign output_stream_TDEST_int_regslice = 'bx;

assign output_stream_TID_int_regslice = 'bx;

assign output_stream_TUSER_int_regslice = 'bx;

assign output_stream_TVALID = regslice_both_output_stream_V_data_V_U_vld_out;

assign select_ln41_fu_540_p3 = ((icmp_ln41_fu_534_p2[0:0] == 1'b1) ? trunc_ln41_fu_530_p1 : 31'd0);

assign select_ln54_fu_631_p3 = ((icmp_ln54_fu_625_p2[0:0] == 1'b1) ? trunc_ln54_fu_621_p1 : 31'd0);

assign sext_ln40_fu_520_p1 = $signed(l1_bias_q0);

assign sext_ln53_fu_611_p1 = $signed(l2_bias_q0);

assign tmp_1_fu_474_p3 = {{j_fu_148}, {3'd0}};

assign tmp_2_fu_576_p3 = {{trunc_ln45_fu_559_p1}, {3'd0}};

assign trunc_ln32_fu_498_p1 = j_fu_148[1:0];

assign trunc_ln41_fu_530_p1 = add_ln40_fu_524_p2[30:0];

assign trunc_ln45_1_fu_589_p1 = j_1_fu_216[1:0];

assign trunc_ln45_fu_559_p1 = j_1_fu_216[4:0];

assign trunc_ln54_fu_621_p1 = add_ln53_fu_615_p2[30:0];

assign zext_ln32_1_fu_510_p1 = lshr_ln1_reg_722;

assign zext_ln32_fu_494_p1 = j_fu_148;

assign zext_ln38_fu_470_p1 = j_fu_148;

assign zext_ln45_1_fu_601_p1 = lshr_ln2_reg_757;

assign zext_ln45_fu_585_p1 = j_1_fu_216;

always @ (posedge ap_clk) begin
    tmp_2_reg_748[2:0] <= 3'b000;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "predict_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //predict

