-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity predict_l1_bias_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of predict_l1_bias_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101111111100101", 1 => "0010100000100011", 2 => "1101010101010110", 3 => "0011110011101110", 
    4 => "0010111101110111", 5 => "0101010001011011", 6 => "1100111101010010", 7 => "0001010100001111", 
    8 => "0010010010111110", 9 => "1111000010000011", 10 => "0001111110010010", 11 => "0001010011111111", 
    12 => "0001000111010001", 13 => "0011111101101001", 14 => "0000101011000000", 15 => "1111111110111000", 
    16 => "1100110100011100", 17 => "1110011101000101", 18 => "1101010011101110", 19 => "1101111011010011", 
    20 => "1100111001001111", 21 => "1111001111111101", 22 => "1111111101001000", 23 => "1110101101110101", 
    24 => "1111001100111100", 25 => "1101101011000100", 26 => "0000100101011000", 27 => "1110111000000000", 
    28 => "1110111011001000", 29 => "0011001000010100", 30 => "0000111100010011", 31 => "1100111001000001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

